# Generated by Django 6.0.3 on 2026-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_model_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
