# Generated by Django 6.0.3 on 2026-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_model_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
