# Generated by Django 6.0.3 on 2026-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_model_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='due_date',
        ),
    ]
