# Generated by Django 6.0.3 on 2026-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_task_model_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task_model',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
